"""Evidence hashing and legal-context lookup."""

from __future__ import annotations

import hashlib
import json
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


KNOWLEDGE_PATH = Path(__file__).resolve().parent / "knowledge" / "legal_context.json"


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def make_evidence(old_bytes: bytes, new_bytes: bytes, scan_id: str | None = None) -> dict[str, Any]:
    old_hash = sha256_bytes(old_bytes)
    new_hash = sha256_bytes(new_bytes)
    combined = sha256_bytes((old_hash + new_hash).encode("utf-8"))
    sid = scan_id or f"PL-{uuid.uuid4().hex[:12].upper()}"
    return {
        "scan_id": sid,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "old_document_sha256": old_hash,
        "new_document_sha256": new_hash,
        "combined_sha256": combined,
        "algorithm": "SHA-256",
        "disclaimer": "Evidence record of uploaded bytes. Not a legal certification.",
    }


def load_legal_context() -> dict[str, Any]:
    if not KNOWLEDGE_PATH.exists():
        return {}
    return json.loads(KNOWLEDGE_PATH.read_text(encoding="utf-8"))


def attach_legal_context(findings: list[dict[str, Any]]) -> list[dict[str, Any]]:
    kb = load_legal_context()
    out = []
    for f in findings:
        item = dict(f)
        ctx = kb.get(f.get("rule_id") or "", None)
        if ctx:
            item["legal_context"] = {
                **ctx,
                "label": "Informational reference — not a legal determination",
            }
        else:
            item["legal_context"] = {
                "title": "General contract change",
                "note": "Compare against your signed baseline. Informational reference only.",
                "refs": [],
                "label": "Informational reference — not a legal determination",
            }
        out.append(item)
    return out


def build_legal_aid_handoff(
    scan_meta: dict[str, Any],
    findings: list[dict[str, Any]],
    evidence: dict[str, Any],
) -> dict[str, Any]:
    """Structured case summary for NGO / legal-aid intake."""
    return {
        "schema": "pactlens.legal_aid_handoff.v1",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "disclaimer": "Informational case summary generated by PactLens. Not legal advice or certification.",
        "contract": {
            "name": scan_meta.get("contract_name"),
            "type": scan_meta.get("contract_type"),
            "scan_id": evidence.get("scan_id"),
        },
        "evidence": evidence,
        "risk_counts": scan_meta.get("risk_counts"),
        "findings": [
            {
                "rule_id": f.get("rule_id"),
                "rule_name": f.get("rule_name"),
                "severity": f.get("severity"),
                "reason": f.get("reason"),
                "old_text": f.get("old_text"),
                "new_text": f.get("new_text"),
                "impact": f.get("impact"),
                "legal_context": f.get("legal_context"),
                "explanation_en": f.get("explanation_en"),
                "explanation_hi": f.get("explanation_hi"),
            }
            for f in findings
            if f.get("severity") in ("High", "Medium", "Low")
        ],
    }
